// Sample fraud case data for ATP FraudTrail Mapper
export const SAMPLE_CASE = {
  complaint_id: "ATP-CC-2026-0042",
  victim_name: "Ramesh Kumar Reddy",
  victim_account: "ACC-VIC-001",
  victim_bank: "State Bank of India",
  victim_mobile: "9876XXXX01",
  victim_age: 67,
  citizen_segment: "senior_citizen",
  fraud_amount: 50000,
  fraud_timestamp: "2026-03-25T14:30:00",
  fraud_type: "otp_fraud",
  suspected_scam_calls: 5,
  suspected_phishing_messages: 3,
  prior_fraud_complaints: 1,
  repeat_otp_exposure: 2,
  digital_literacy: "low",
  status: "investigating",
  recovered_amount: 12500,
  frozen_accounts_count: 3,
  total_accounts_involved: 9,
  investigating_officer: "SI Venkatesh Goud",
};

export const SAMPLE_ACCOUNTS = [
  {
    account_number: "ACC-VIC-001",
    account_holder_name: "Ramesh Kumar Reddy",
    mobile_number: "9876XXXX01",
    email: "ramesh.r@email.com",
    kyc_id_masked: "XXXX-XXXX-4521",
    bank_name: "State Bank of India",
    account_creation_date: "2019-03-15",
    current_balance: 2340,
    account_status: "active",
    classification: "victim",
    risk_score: 0,
    trust_score: 95,
    transaction_velocity: 0.5,
    chain_depth_level: 0,
    freeze_priority: 0,
    case_id: "ATP-CC-2026-0042",
    ip_address: "103.21.58.12",
    device_id: "DEV-SAMSUNG-A52",
    location: "Anantapur, AP",
    login_timestamp: "2026-03-25T14:25:00",
  },
  {
    account_number: "ACC-MAS-002",
    account_holder_name: "Suresh Babu",
    mobile_number: "9988XXXX02",
    email: "s.babu@fakemail.com",
    kyc_id_masked: "XXXX-XXXX-7832",
    bank_name: "HDFC Bank",
    account_creation_date: "2025-11-20",
    current_balance: 890,
    account_status: "frozen",
    classification: "mastermind",
    risk_score: 95,
    trust_score: 5,
    transaction_velocity: 12,
    chain_depth_level: 1,
    freeze_priority: 10,
    case_id: "ATP-CC-2026-0042",
    ip_address: "45.33.92.18",
    device_id: "DEV-XIAOMI-NOTE12",
    location: "Kurnool, AP",
    login_timestamp: "2026-03-25T14:32:00",
  },
  {
    account_number: "ACC-SPL-003",
    account_holder_name: "Nagaraju M",
    mobile_number: "9877XXXX03",
    email: "nag.m@email.com",
    kyc_id_masked: "XXXX-XXXX-1245",
    bank_name: "ICICI Bank",
    account_creation_date: "2025-12-05",
    current_balance: 450,
    account_status: "frozen",
    classification: "splitter",
    risk_score: 82,
    trust_score: 12,
    transaction_velocity: 8,
    chain_depth_level: 2,
    freeze_priority: 8,
    case_id: "ATP-CC-2026-0042",
    ip_address: "45.33.92.18",
    device_id: "DEV-XIAOMI-NOTE12",
    location: "Kurnool, AP",
    login_timestamp: "2026-03-25T14:35:00",
  },
  {
    account_number: "ACC-SPL-004",
    account_holder_name: "Lakshmi Devi",
    mobile_number: "9866XXXX04",
    email: "lakshmi.d@email.com",
    kyc_id_masked: "XXXX-XXXX-9087",
    bank_name: "Axis Bank",
    account_creation_date: "2026-01-10",
    current_balance: 200,
    account_status: "active",
    classification: "splitter",
    risk_score: 78,
    trust_score: 15,
    transaction_velocity: 6,
    chain_depth_level: 2,
    freeze_priority: 7,
    case_id: "ATP-CC-2026-0042",
    ip_address: "122.15.67.45",
    device_id: "DEV-OPPO-A78",
    location: "Guntakal, AP",
    login_timestamp: "2026-03-25T14:34:00",
  },
  {
    account_number: "ACC-MUL-005",
    account_holder_name: "Venkata Rao",
    mobile_number: "9854XXXX05",
    email: "v.rao@email.com",
    kyc_id_masked: "XXXX-XXXX-3456",
    bank_name: "Kotak Mahindra",
    account_creation_date: "2026-02-28",
    current_balance: 0,
    account_status: "active",
    classification: "mule",
    risk_score: 70,
    trust_score: 20,
    transaction_velocity: 4,
    chain_depth_level: 3,
    freeze_priority: 6,
    case_id: "ATP-CC-2026-0042",
    ip_address: "182.73.21.99",
    device_id: "DEV-VIVO-Y21",
    location: "Dharmavaram, AP",
    login_timestamp: "2026-03-25T14:40:00",
  },
  {
    account_number: "ACC-MUL-006",
    account_holder_name: "Pradeep Singh",
    mobile_number: "9843XXXX06",
    email: "p.singh@email.com",
    kyc_id_masked: "XXXX-XXXX-6789",
    bank_name: "Punjab National Bank",
    account_creation_date: "2026-03-01",
    current_balance: 150,
    account_status: "active",
    classification: "mule",
    risk_score: 65,
    trust_score: 25,
    transaction_velocity: 3,
    chain_depth_level: 3,
    freeze_priority: 5,
    case_id: "ATP-CC-2026-0042",
    ip_address: "103.55.12.78",
    device_id: "DEV-SAMSUNG-M13",
    location: "Anantapur, AP",
    login_timestamp: "2026-03-25T14:42:00",
  },
  {
    account_number: "ACC-CSH-007",
    account_holder_name: "Abdul Karim",
    mobile_number: "9832XXXX07",
    email: "a.karim@email.com",
    kyc_id_masked: "XXXX-XXXX-2345",
    bank_name: "Bank of Baroda",
    account_creation_date: "2025-06-15",
    current_balance: 0,
    account_status: "active",
    classification: "cashout",
    risk_score: 88,
    trust_score: 8,
    transaction_velocity: 2,
    chain_depth_level: 4,
    freeze_priority: 9,
    case_id: "ATP-CC-2026-0042",
    ip_address: "49.207.33.55",
    device_id: "DEV-REALME-9",
    location: "Hyderabad, TS",
    login_timestamp: "2026-03-25T14:50:00",
  },
  {
    account_number: "ACC-CSH-008",
    account_holder_name: "Srinivas Murthy",
    mobile_number: "9821XXXX08",
    email: "s.murthy@email.com",
    kyc_id_masked: "XXXX-XXXX-5678",
    bank_name: "Canara Bank",
    account_creation_date: "2024-09-20",
    current_balance: 5200,
    account_status: "active",
    classification: "cashout",
    risk_score: 72,
    trust_score: 18,
    transaction_velocity: 2,
    chain_depth_level: 4,
    freeze_priority: 7,
    case_id: "ATP-CC-2026-0042",
    ip_address: "103.55.12.78",
    device_id: "DEV-SAMSUNG-M13",
    location: "Anantapur, AP",
    login_timestamp: "2026-03-25T14:52:00",
  },
  {
    account_number: "ACC-INN-009",
    account_holder_name: "Padmavathi G",
    mobile_number: "9810XXXX09",
    email: "padma.g@email.com",
    kyc_id_masked: "XXXX-XXXX-8901",
    bank_name: "State Bank of India",
    account_creation_date: "2018-04-10",
    current_balance: 45000,
    account_status: "active",
    classification: "innocent",
    risk_score: 12,
    trust_score: 88,
    transaction_velocity: 0.3,
    chain_depth_level: 3,
    freeze_priority: 1,
    case_id: "ATP-CC-2026-0042",
    ip_address: "223.186.45.12",
    device_id: "DEV-IPHONE-14",
    location: "Anantapur, AP",
    login_timestamp: "2026-03-25T15:10:00",
  },
];

export const SAMPLE_TRANSACTIONS = [
  {
    transaction_id: "TXN-001",
    sender_account: "ACC-VIC-001",
    receiver_account: "ACC-MAS-002",
    amount: 50000,
    timestamp: "2026-03-25T14:31:00",
    transaction_type: "UPI",
    transaction_status: "success",
    reference_id: "UTR-928374650001",
    case_id: "ATP-CC-2026-0042",
    is_suspicious: true,
    flag_reason: "Full fraud amount transferred in single UPI transaction",
  },
  {
    transaction_id: "TXN-002",
    sender_account: "ACC-MAS-002",
    receiver_account: "ACC-SPL-003",
    amount: 25000,
    timestamp: "2026-03-25T14:33:00",
    transaction_type: "IMPS",
    transaction_status: "success",
    reference_id: "UTR-928374650002",
    case_id: "ATP-CC-2026-0042",
    is_suspicious: true,
    flag_reason: "Rapid split within 2 minutes of receiving",
  },
  {
    transaction_id: "TXN-003",
    sender_account: "ACC-MAS-002",
    receiver_account: "ACC-SPL-004",
    amount: 24000,
    timestamp: "2026-03-25T14:33:30",
    transaction_type: "IMPS",
    transaction_status: "success",
    reference_id: "UTR-928374650003",
    case_id: "ATP-CC-2026-0042",
    is_suspicious: true,
    flag_reason: "Rapid split within 2.5 minutes",
  },
  {
    transaction_id: "TXN-004",
    sender_account: "ACC-SPL-003",
    receiver_account: "ACC-MUL-005",
    amount: 12000,
    timestamp: "2026-03-25T14:36:00",
    transaction_type: "UPI",
    transaction_status: "success",
    reference_id: "UTR-928374650004",
    case_id: "ATP-CC-2026-0042",
    is_suspicious: true,
    flag_reason: "Further splitting detected",
  },
  {
    transaction_id: "TXN-005",
    sender_account: "ACC-SPL-003",
    receiver_account: "ACC-MUL-006",
    amount: 8000,
    timestamp: "2026-03-25T14:37:00",
    transaction_type: "UPI",
    transaction_status: "success",
    reference_id: "UTR-928374650005",
    case_id: "ATP-CC-2026-0042",
    is_suspicious: true,
    flag_reason: "Continued splitting pattern",
  },
  {
    transaction_id: "TXN-006",
    sender_account: "ACC-SPL-003",
    receiver_account: "ACC-INN-009",
    amount: 5000,
    timestamp: "2026-03-25T14:38:00",
    transaction_type: "UPI",
    transaction_status: "success",
    reference_id: "UTR-928374650006",
    case_id: "ATP-CC-2026-0042",
    is_suspicious: false,
    flag_reason: "Appears to be a legitimate payment",
  },
  {
    transaction_id: "TXN-007",
    sender_account: "ACC-SPL-004",
    receiver_account: "ACC-CSH-007",
    amount: 15000,
    timestamp: "2026-03-25T14:39:00",
    transaction_type: "IMPS",
    transaction_status: "success",
    reference_id: "UTR-928374650007",
    case_id: "ATP-CC-2026-0042",
    is_suspicious: true,
    flag_reason: "Large transfer to suspected cashout account",
  },
  {
    transaction_id: "TXN-008",
    sender_account: "ACC-SPL-004",
    receiver_account: "ACC-CSH-008",
    amount: 9000,
    timestamp: "2026-03-25T14:40:00",
    transaction_type: "UPI",
    transaction_status: "success",
    reference_id: "UTR-928374650008",
    case_id: "ATP-CC-2026-0042",
    is_suspicious: true,
    flag_reason: "Transfer to suspected cashout account",
  },
  {
    transaction_id: "TXN-009",
    sender_account: "ACC-MUL-005",
    receiver_account: "ACC-CSH-007",
    amount: 12000,
    timestamp: "2026-03-25T14:45:00",
    transaction_type: "NEFT",
    transaction_status: "success",
    reference_id: "UTR-928374650009",
    case_id: "ATP-CC-2026-0042",
    is_suspicious: true,
    flag_reason: "Full balance forwarded to cashout",
  },
  {
    transaction_id: "TXN-010",
    sender_account: "ACC-MUL-006",
    receiver_account: "ACC-CSH-008",
    amount: 7500,
    timestamp: "2026-03-25T14:48:00",
    transaction_type: "UPI",
    transaction_status: "success",
    reference_id: "UTR-928374650010",
    case_id: "ATP-CC-2026-0042",
    is_suspicious: true,
    flag_reason: "Near-total balance forwarded",
  },
];

export const SAMPLE_ALERTS = [
  {
    alert_type: "rapid_transfer",
    severity: "critical",
    account_number: "ACC-MAS-002",
    case_id: "ATP-CC-2026-0042",
    description: "₹50,000 split into 2 transactions within 30 seconds of receipt",
    is_read: false,
    action_taken: "frozen",
  },
  {
    alert_type: "shared_device",
    severity: "high",
    account_number: "ACC-SPL-003",
    case_id: "ATP-CC-2026-0042",
    description: "Same device ID (DEV-XIAOMI-NOTE12) used for ACC-MAS-002 and ACC-SPL-003",
    is_read: false,
    action_taken: "frozen",
  },
  {
    alert_type: "new_account",
    severity: "high",
    account_number: "ACC-MUL-006",
    case_id: "ATP-CC-2026-0042",
    description: "Account created only 24 days before fraud — potential mule account",
    is_read: true,
    action_taken: "flagged",
  },
  {
    alert_type: "large_cashout",
    severity: "critical",
    account_number: "ACC-CSH-007",
    case_id: "ATP-CC-2026-0042",
    description: "₹27,000 aggregated from multiple chains — suspected major cashout point",
    is_read: false,
    action_taken: "none",
  },
  {
    alert_type: "high_velocity",
    severity: "high",
    account_number: "ACC-MAS-002",
    case_id: "ATP-CC-2026-0042",
    description: "12 transactions/hour detected — abnormal velocity for this account type",
    is_read: true,
    action_taken: "frozen",
  },
  {
    alert_type: "multi_location",
    severity: "medium",
    account_number: "ACC-CSH-007",
    case_id: "ATP-CC-2026-0042",
    description: "Account accessed from Hyderabad while linked accounts are in Anantapur region",
    is_read: false,
    action_taken: "none",
  },
  {
    alert_type: "deep_chain",
    severity: "medium",
    account_number: "ACC-CSH-008",
    case_id: "ATP-CC-2026-0042",
    description: "Transaction chain depth reached level 4 — money trail becoming complex",
    is_read: false,
    action_taken: "flagged",
  },
  {
    alert_type: "pattern_match",
    severity: "high",
    account_number: "ACC-SPL-004",
    case_id: "ATP-CC-2026-0042",
    description: "Splitting pattern matches known fraud ring signature from case ATP-CC-2026-0031",
    is_read: false,
    action_taken: "none",
  },
];

// Helper to get classification color
export const getClassificationColor = (classification) => {
  const colors = {
    victim: { bg: "bg-blue-500/20", text: "text-blue-400", border: "border-blue-500/30" },
    mastermind: { bg: "bg-red-500/20", text: "text-red-400", border: "border-red-500/30" },
    splitter: { bg: "bg-orange-500/20", text: "text-orange-400", border: "border-orange-500/30" },
    mule: { bg: "bg-yellow-500/20", text: "text-yellow-400", border: "border-yellow-500/30" },
    cashout: { bg: "bg-purple-500/20", text: "text-purple-400", border: "border-purple-500/30" },
    innocent: { bg: "bg-green-500/20", text: "text-green-400", border: "border-green-500/30" },
    unknown: { bg: "bg-gray-500/20", text: "text-gray-400", border: "border-gray-500/30" },
  };
  return colors[classification] || colors.unknown;
};

export const getSeverityColor = (severity) => {
  const colors = {
    critical: { bg: "bg-red-500/20", text: "text-red-400", dot: "bg-red-500" },
    high: { bg: "bg-orange-500/20", text: "text-orange-400", dot: "bg-orange-500" },
    medium: { bg: "bg-yellow-500/20", text: "text-yellow-400", dot: "bg-yellow-500" },
    low: { bg: "bg-blue-500/20", text: "text-blue-400", dot: "bg-blue-500" },
  };
  return colors[severity] || colors.medium;
};

export const getRiskColor = (score) => {
  if (score >= 80) return "text-red-400";
  if (score >= 60) return "text-orange-400";
  if (score >= 40) return "text-yellow-400";
  if (score >= 20) return "text-blue-400";
  return "text-green-400";
};
